version: 2
jobs:
  build:
    docker:
      - image: "rikorose/gcc-cmake:latest"
    branches:
      only:
      - feature/add_circle-ci_support
    steps:
      - run:
          name: Listing0
          command: 'pwd'
      - run:
          name: Creating Build Files
          command: 'cmake -Bbuild etlcpp/test/'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Listing1
          command: 'ls -lrt /root/project/build'
      - run:
          name: Listing2
          command: 'ls -lrt /root/project/build/CMakeFiles'
      - run:
          name: Listing3
          command: 'cat /root/project/build/CMakeFiles/CMakeOutput.log' 
      - run:
          name: ETL Unit Testing
          command: './bin/etl'