name: CI
on:
  push:
    branches: [ feature/github-actions-for-windows-compilers ]
  pull_request:
    branches: [ master ]

jobs:

  build-windows-vs2019:
    name: Windows VS2019 Debug
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Checkout UnitTest++
      run: |
        echo ${GITHUB_WORKSPACE}
        echo ::set-env name=workspace::$GITHUB_WORKSPACE
      uses: actions/checkout@v2
      with:
        repository: unittest-cpp/unittest-cpp
        path: ${{ env.workspace }}/../../../unittest-cpp

    - name: Build
      run: MSBuild.exe test/vs2019/etl.sln

    - name: Run tests
      run: ./test/etl_tests

