name: CI
on:
  push:
    branches: [ feature/github-actions-for-windows-compilers ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-vs2019:
    name: Windows VS2019 Debug
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Installing vcpkg
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2020.01
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install cppzmq:x64-windows

    - name: Build
      run: |
        cd ${{ github.workspace }}
        MSBuild.exe etl.sln /property:Configuration=Debug

    - name: Run tests
      run: ./test/etl_tests
