name: CI
on:
  push:
    branches: [ feature/github-actions-for-windows-compilers ]
  pull_request:
    branches: [ master ]

jobs:

  build-visual-studio:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build and run
      run: |
        cmake -DBUILD_TESTS=ON ./
        cd test/vs2019
        dir
        MSBuild etl.sln /property:Configuration=Debug /property:Platform="Any CPU"

