name: CI
on:
  push:
    branches: [ feature/no-stl-variants-for-github-ci ]
  pull_request:
    branches: [ master ]

jobs:
  build-gcc-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cmake -DBUILD_TESTS=ON ./
        gcc --version
        make
    
    - name: Run tests
      run: ./test/etl_tests

  build-gcc-linux-no-stl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Build and run
      run: |
        cmake -DBUILD_TESTS=ON -DNO_STL=ON ./
        gcc --version
        make
    
    - name: Run tests
      run: ./test/etl_tests

  build-clang-9-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export CC=clang-9
        export CXX=clang++-9
        cmake -D BUILD_TESTS=ON ./
        clang --version
        make

    - name: Run tests
      run: ./test/etl_tests

  build-clang-9-linux-no-stl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: Build and run
      run: |
        export CC=clang-9
        export CXX=clang++-9
        cmake -D BUILD_TESTS=ON -DNO_STL=ON ./
        clang --version
        make

    - name: Run tests
      run: ./test/etl_tests

  build-clang-10-osx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        export CC=clang
        export CXX=clang++
        cmake -D BUILD_TESTS=ON ./
        clang --version
        make

    - name: Run tests
      run: ./test/etl_tests

  build-clang-10-osx-no-stl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]

    steps:
    - uses: actions/checkout@v2

    - name: Build and run
      run: |
        export CC=clang
        export CXX=clang++
        cmake -D BUILD_TESTS=ON -DNO_STL=ON ./
        clang --version
        make

    - name: Run tests
      run: ./test/etl_tests
