name: CI
on:
  push:
    branches: [ feature/github-actions-for-windows-compilers ]
  pull_request:
    branches: [ master ]

jobs:

  build-visual-studio:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Running cmake
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}

    - name: Build and run
      run: |
        cmake -D BUILD_TESTS=ON ./
        cd build
        MSBuild.exe etl.sln
