name: CI
on:
  push:
    branches: [ feature/github-actions-for-windows-compilers ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-vs2019:
    name: Windows VS2019 Debug
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build and run
      run: |
        cmake -G "Visual Studio 16 2019" -D BUILD_TESTS=ON ./
        make


