name: CI
on:
  push:
    branches: [ hotfix/fix-ci-errors]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: name: Build and run
      run: |
        cmake -DBUILD_TESTS=ON ./
        gcc --version
        make
    
    - name: Run tests
      run: ./test/etl_tests

  build-clang-9-Linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build and run
      run: |
        export CC=clang-9
        export CXX=clang++-9
        cmake -D BUILD_TESTS=ON ./
        clang --version
        make

    - name: Run tests
      run: ./test/etl_tests

  build-clang-10-osx:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2

    - name: Build and run
      run: |
        export CC=clang
        export CXX=clang++
        cmake -D BUILD_TESTS=ON ./
        clang --version
        make

    - name: Run tests
      run: ./test/etl_tests

