name: CI
on:
  push:
    branches: [ feature/github-actions-for-windows-compilers ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows-vs2019:
    name: Windows VS2019 Debug
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Binary
      run: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Debug /p:Platform=x86

    - name: Run tests
      run: ./test/etl_tests
