name: CI
on:
  push:
    branches: [feature/github-actions-for-windows-compilers ]
  pull_request:
    branches: [ master ]

jobs:

  build-visual-studio:
    runs-on: [windows]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Installing vcpkg
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2020.01
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install cppzmq:x64-windows

    - name: Running cmake
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}
                  /../vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build and run
      run: |
        cmake -D BUILD_TESTS=ON ./
        cd build
        MSBuild.exe etl.sln
