name: CI
on:
  push:
    branches: [ feature/github-actions-for-windows-compilers ]
  pull_request:
    branches: [ master ]

jobs:

  build-visual-studio:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build and run
      working-directory: test/vs2019
      run: |
        msbuild etl.sln /p:Configuration=DebugNoSTL /p:Platform="Any CPU"
